---
- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: Disk usage from command module
            command: du -hsx /var/lib/docker/overlay/* | sort -rh | head -10
            register: space
          - debug:
                  var: space.stdout_lines
